Cleanup motes-convert

diff --git a/motes-build b/motes-build
--- a/motes-build
+++ b/motes-build
@@ -6,9 +6,9 @@
 
 set -e
 
-# Retrieve the arguments.
+# Ensure that the arguments are correct.
 if [ -z "$2" ]; then
-    echo "usage: $0 SRC-DIR DEST-DIR"
+    >&2 echo "usage: $0 SRC-DIR DEST-DIR"
     exit 1
 fi
 
@@ -17,7 +17,7 @@ dest="$2"
 
 # Ensure that the source directory exists.
 if [ ! -d "$src" ]; then
-    echo "$0: Failed to find source directory $src to build from"
+    >&2 echo "$0: Failed to find source directory $src to build from"
     exit 1
 fi
 
diff --git a/motes-convert b/motes-convert
--- a/motes-convert
+++ b/motes-convert
@@ -6,28 +6,28 @@ set -e
 
 # Ensure that there are enough arguments.
 if [ -z  "$2" ]; then
-    echo "usage: $0 IN-FILE OUT-FILE"
+    >&2 echo "usage: $0 IN-FILE OUT-FILE"
     exit 1
 fi
 
 # Ensure that the file extensions are correct.
 in_ext="${1##*.}"
 if [ "$in_ext" != "md" ]; then
-    echo "$0: Cannot build file $1 with extension $in_ext"
-    echo "$0: (HINT) Only Markdown files are accepted as input (they end with .md)"
+    >&2 echo "$0: Cannot build file $1 with extension $in_ext"
+    >&2 echo "$0: Only Markdown files are accepted as input (they end with .md)"
     exit 1
 fi
 
 out_ext="${2##*.}"
 if [ "$out_ext" != "html" ]; then
-    echo "$0: Cannot output file $2 with extension $out_ext"
-    echo "$0: (HINT) Only HTML files are accepted as output (they end with .html)"
+    >&2 echo "$0: Cannot output file $2 with extension $out_ext"
+    >&2 echo "$0: Only HTML files are accepted as output (they end with .html)"
     exit 1
 fi
 
 # Ensure `pandoc` exists.
 if [ -z "$(which pandoc)" ]; then
-    echo "$0: pandoc is not installed"
+    >&2 echo "$0: pandoc is not installed"
     exit 1
 fi
 
@@ -40,11 +40,11 @@ if [ -n "$(which mermaid-filter)" ]; then
     export MERMAID_FILTRE_FORMAT="svg"
     export MERMAID_FILTER_THEME="forest"
     filter+="--filter=mermaid-filter"
-    # Cleanup the annoying mermaid-filter.err file created by mermaid-filter if it's just empty.
-    trap '[ "$(cat mermaid-filter.err)" == "" ] && rm -f mermaid-filter.err' EXIT
+    # Remove mermaid-filter.err if it was created but is empty.
+    trap '[[ -f mermaid-filter.err && ! -s mermaid-filter.err ]] && rm -f mermaid-filter.err' EXIT
 else
-    echo "$0: (WARN) mermaid-filter is not installed, and will not be used"
-    echo "$0: (HINT) Install it from here: https://github.com/raghur/mermaid-filter"
+    >&2 echo "$0: Warning: mermaid-filter is not installed, and will not be used"
+    >&2 echo "$0: Install it from here: https://github.com/raghur/mermaid-filter"
 fi
 
 pandoc --from=markdown \
@@ -53,6 +53,7 @@ pandoc --from=markdown \
        --template=template.html \
        --include-in-header=style.html \
        --mathjax \
+       # Don't quote $filter, so it fully disappears when empty.
        $filter \
        --output="$2" \
        "$1"
diff --git a/motes-preview b/motes-preview
--- a/motes-preview
+++ b/motes-preview
@@ -9,19 +9,19 @@ set -e
 
 # Ensure arguments are OK.
 if [ -z  "$1" ]; then
-    echo "usage: $0 NOTE-FILE"
+    >&2 echo "usage: $0 NOTE-FILE"
     exit 1
 fi
 
 # Ensure the `inotifywait` command exists.
 if [ -z "$(which inotifywait)" ]; then
-    echo "$0: inotifywait is not installed"
+    >&2 echo "$0: inotifywait is not installed"
     exit 1
 fi
 
 # Ensure the python exists.
 if [ -z "$(which python)" ]; then
-    echo "$0: python is not installed"
+    >&2 echo "$0: python is not installed"
     exit 1
 fi
 
@@ -30,7 +30,7 @@ fi
 filename=$(basename -- "$1")
 outfile=$(mktemp --quiet --tmpdir=/tmp "XXXXXX${filename%.md}.html")
 if [ $? -ne 0 ]; then
-    echo "$0: Cannot create temporary output file"
+    >&2 echo "$0: Cannot create temporary output file"
     exit 1
 fi
 
